const courses = [
    { name: 'Accountancy/Accounting' },
    { name: 'Actuarial Science' },
    { name: 'Banking/Finance' },
    { name: 'Banking, Finance and Insurance' },
    { name: 'Business Administration' },
    { name: 'Business Management' },
    { name: 'Business Economics' },
    { name: 'Cooperative and Rural Development' },
    { name: 'Cooperative Economics and Management' },
    { name: 'Economics' },
    { name: 'Entrepreneurship' },
    { name: 'Film and Video Studies' },
    { name: 'Finance' },
    { name: 'Human Resources Management' },
    { name: 'Hotel Tourism Management' },
    { name: 'Industrial Relations and Personnel Management' },
    { name: 'Insurance' },
    { name: 'Insurance and Risk Management' },
    { name: 'International Relations' },
    { name: 'International Relations and Strategic Studies' },
    { name: 'Local Government Administration' },
    { name: 'Mass Communication' },
    { name: 'Media Studies and Mass Communication' },
    { name: 'Management Studies' },
    { name: 'Marketing' },
    { name: 'Office Management Technology' },
    { name: 'Public Administration' },
    { name: 'Public Relations and Advertising' },
    { name: 'Secretarial Administration' },
    { name: 'Transport and Tourism' },
    { name: 'Agriculture' },
    { name: 'Agricultural Administration' },
    { name: 'Fisheries Management' },
    { name: 'Fisheries' },
    { name: 'Fisheries and Aquatic Resources Management' },
    { name: 'Fisheries Technology' },
    { name: 'Agricultural Cooperative Management' },
    { name: 'Fisheries and Agriculture' },
    { name: 'Fisheries and Aquatic Environmental Management' },
    { name: 'Agricultural Economics' },
    { name: 'Agricultural Economics and Farm Management' },
    { name: 'Agricultural Administration' },
    { name: 'Agricultural Economics and Extension' },
    { name: 'Agricultural Extension and Rural Sociology' },
    { name: 'Agricultural Extension and Management' },
    { name: 'Agricultural Extension' },
    { name: 'Agricultural Extension Service' },
    { name: 'Agricultural Extension and Rural Development' },
    { name: 'Agricultural Extension and Communication Technology' },
    { name: 'Agricultural Extension and Social Engineering' },
    { name: 'Agronomy' },
    { name: 'Animal Production and Health Services' },
    { name: 'Animal Production and Health' },
    { name: 'Animal Production' },
    { name: 'Animal Production and Fisheries' },
    { name: 'Livestock Production Technology' },
    { name: 'Pasture and Range Management' },
    { name: 'Animal Nutrition' },
    { name: 'Animal Nutrition and Biotechnology' },
    { name: 'Animal Science and Range Management' },
    { name: 'Animal Science' },
    { name: 'Animal Science and Fisheries Management' },
    { name: 'Animal Science and Technology' },
    { name: 'Animal Physiology' },
    { name: 'Animal Breeding and Genetics' },
    { name: 'Animal Science and Fisheries' },
    { name: 'Crop Production' },
    { name: 'Crop, Soil and Pest Management' },
    { name: 'Crop Production and Landscape Management' },
    { name: 'Crop Production and Horticulture' },
    { name: 'Crop Production and Protection' },
    { name: 'Crop Protection' },
    { name: 'Crop Science' },
    { name: 'Crop Science/Soil Science' },
    { name: 'Crop Science and Horticulture' },
    { name: 'Crop and Environmental Protection' },
    { name: 'Plant Breeding and Seed Technology' },
    { name: 'Crop Production and Soil Science' },
    { name: 'Crop Production Technology' },
    { name: 'Crop Science and Technology' },
    { name: 'African and Asian Studies' },
    { name: 'Archaeology' },
    { name: 'Anthropology' },
    { name: 'Arabic Studies' },
    { name: 'Arabic Language and Literature' },
    { name: 'Arabic and IS' },
    { name: 'Arts (Combined)' },
    { name: 'Christian Religious Knowledge/Studies' },
    { name: 'Christian Studies' },
    { name: 'Classical Studies' },
    { name: 'Communication Arts' },
    { name: 'Communication and Language Arts' },
    { name: 'Comparative Religious Studies' },
    { name: 'Counselling and Psychology' },
    { name: 'Creative Arts' },
    { name: 'Drama, Dramatic Arts, Theatre Arts and Performing Arts' },
    { name: 'Afik-Ibibio' },
    { name: 'English Language' },
    { name: 'English Language and Literature' },
    { name: 'English Studies' },
    { name: 'English and Literary Studies' },
    { name: 'English and International Studies' },
    { name: 'Economics' },
    { name: 'Fine Arts/Fine and Applied Arts' },
    { name: 'Foreign Language and Literature' },
    { name: 'French' },
    { name: 'French and International Relations' },
    { name: 'French and German/Russian' },
    { name: 'Fulfude' },
    { name: 'Geography and Environmental Studies' },
    { name: 'German' },
    { name: 'Hausa' },
    { name: 'History' },
    { name: 'History and Archeology' },
    { name: 'History/International Studies' },
    { name: 'History and Diplomacy' },
    { name: 'History and Diplomatic Studies' },
    { name: 'History and Strategic Studies' },
    { name: 'History and Political Studies' },
    { name: 'Igbo' },
    { name: 'Igbo/Linguistics' },
    { name: 'International Studies and Diplomacy' },
    { name: 'International and Comparative Politics' },
    { name: 'IS' },
    { name: 'Kanuri' },
    { name: 'Kiswahili' },
    { name: 'Languages' },
    { name: 'Languages Arts' },
    { name: 'Language Arts and Yoruba' },
    { name: 'Language and Linguistics' },
    { name: 'Language and Literature' },
    { name: 'Linguistics' },
    { name: 'Linguistics/Yoruba' },
    { name: 'Linguistics/Edl' },
    { name: 'Linguistics/Urhobo' },
    { name: 'Literature in English' },
    { name: 'Mass Communication' },
    { name: 'Modern European Languages' },
    { name: 'Modern Language and Translation' },
    { name: 'Music' },
    { name: 'Peace Studies' },
    { name: 'Philosophy' },
    { name: 'Philosophy and Religious Studies' },
    { name: 'Political Science and Conflict Resolution' },
    { name: 'Psychology and Human Development' },
    { name: 'Portuguese' },
    { name: 'Portuguese/English' },
    { name: 'Religion and Philosophy' },
    { name: 'Religion and Science' },
    { name: 'Religious Studies' },
    { name: 'Religious Studies/Theology' },
    { name: 'Russian with French/German' },
    { name: 'Sociology' },
    { name: 'Theology' },
    { name: 'Yoruba' },
    { name: 'Yoruba and Communication' },
    { name: 'Agricultural Engineering' },
    { name: 'Agricultural and Environmental Engineering' },
    { name: 'Agricultural and Bio-Resources Engineering' },
    { name: 'Architecture' },
    { name: 'Biomedical Engineering' },
    { name: 'Building' },
    { name: 'Chemical Engineering' },
    { name: 'Chemical/Petroleum/Petrochemical Engineering' },
    { name: 'Civil Engineering' },
    { name: 'Civil Engineering/Hydrology' },
    { name: 'Computer Engineering' },
    { name: 'Computer Science' },
    { name: 'Computer Science and Engineering' },
    { name: 'Computer Science with (Economics) (Mathematics)' },
    { name: 'Computer and Information Science' },
    { name: 'Communication Technology' },
    { name: 'Communication and Multimedia Advertising' },
    { name: 'Communication and Multimedia Printing Journalism' },
    { name: 'Communication and Multimedia Television/Filming' },
    { name: 'Communication and Multimedia Design' },
    { name: 'Electrical Engineering' },
    { name: 'Electronics Engineering' },
    { name: 'Electrical/Electronics/Computer Engineering' },
    { name: 'Electrical/Electronic Engineering' },
    { name: 'Environmental Management' },
    { name: 'Environmental Engineering' },
    { name: 'Environmental Technology' },
    { name: 'Environmental Management Technology' },
    { name: 'Estate Management' },
    { name: 'Fine Art' },
    { name: 'Fine and Applied Arts' },
    { name: 'Food Engineering' },
    { name: 'Food Science and Technology/Engineering' },
    { name: 'Food Science and Engineering' },
    { name: 'Food Technology' },
    { name: 'Gas Engineering' },
    { name: 'Geography' },
    { name: 'Geography and Regional Planning' },
    { name: 'Geography and Meteorology' },
    { name: 'Geography and Planning' },
    { name: 'Hotel Management and Tourism' },
    { name: 'Home Economics and Food Management' },
    { name: 'ICT Engineering' },
    { name: 'Irrigation Engineering' },
    { name: 'Industrial Arts' },
    { name: 'Industrial Design' },
    { name: 'Industrial Production and Engineering' },
    { name: 'Information Technology' },
    { name: 'Land Surveying' },
    { name: 'Management Technology' },
    { name: 'Marine Engineering' },
    { name: 'Marine Management Technology' },
    { name: 'Materials and Production Engineering' },
    { name: 'Mechanical Engineering' },
    { name: 'Mechatronics Engineering' },
    { name: 'Mechanical and Production Engineering' },
    { name: 'Metallurgical & Material Engineering' },
    { name: 'Metallurgical Engineering' },
    { name: 'Meteorology' },
    { name: 'Mining Engineering' },
    { name: 'Naval Architecture' },
    { name: 'Nutrition and Dietetics' },
    { name: 'Petroleum Engineering' },
    { name: 'Petroleum and Gas Engineering' },
    { name: 'Polymer and Textile Engineering' },
    { name: 'Production Engineering' },
    { name: 'Project Management Technology' },
    { name: 'Quantity Surveying' },
    { name: 'Software Engineering' },
    { name: 'Surveying' },
    { name: 'Surveying and Geo-Informatics' },
    { name: 'Systems Engineering' },
    { name: 'Statistics' },
    { name: 'Transportation and Management Technology' },
    { name: 'Technological Management' },
    { name: 'Urban and Regional Planning' },
    { name: 'Visual Arts technology' },
    { name: 'Water Resources and Environmental Engineering' },
    { name: 'Education Administration and Supervision' },
    { name: 'Adult Education' },
    { name: 'Adult Education/English Literature' },
    { name: 'Adult Education/Economics and Statistics' },
    { name: 'Adult and Community Education' },
    { name: 'Adult Education and Non-Formal Education' },
    {
      name: 'Adult Education/Political Science and Public Administration'
    },
    { name: 'Adult Education/Geography and Regional Planning' },
    { name: 'Curriculum and Teaching' },
    { name: 'Curriculum and Instruction' },
    { name: 'Curriculum Studies' },
    { name: 'Educational Administration' },
    { name: 'Education Foundation and Administration' },
    { name: 'Educational Foundation' },
    { name: 'Education Foundation and Management' },
    { name: 'Education Psychology, Guidance and Counselling' },
    { name: 'Education Management' },
    { name: 'Industrial and Labour Relations' },
    { name: 'Library Science' },
    { name: 'Library and Information Science' },
    { name: 'Library Studies' },
    { name: 'Library and Information Science' },
    { name: 'Library Studies' },
    { name: 'Nursery and Primary Education' },
    { name: 'Pre-Primary Education' },
    { name: 'Primary Education' },
    { name: 'Philosophy Education' },
    { name: 'Psychology Education' },
    { name: 'Psychology Education' },
    { name: 'Science and Computer Education' },
    { name: 'Science Education' },
    { name: 'Special Education (Visual Handicaps)' },
    { name: 'Sport Management' },
    { name: 'Teacher Education' },
    { name: 'Arts and Social Science Education' },
    { name: 'Arts Education' },
    { name: 'Education/Arabic' },
    { name: 'Education/Arts' },
    { name: 'Education/Arts and Social Sciences' },
    { name: 'Education/Arts and Social Sciences' },
    { name: 'Education/Christian Religious Studies' },
    { name: 'Education/Edo Language' },
    { name: 'Education/English Language' },
    { name: 'Education/English Language' },
    { name: 'Education/Fine and Applied Arts' },
    { name: 'Education/French' },
    { name: 'Education/Geography' },
    { name: 'Education/Hausa' },
    { name: 'Education/History' },
    { name: 'Education/Igbo' },
    { name: 'Education/Igbo/Linguistics' },
    { name: 'Education/Language Arts' },
    { name: 'Education/Language and French' },
    { name: 'Education/Language/English' },
    { name: 'Education/Linguistics' },
    { name: 'Education/Linguistics' },
    { name: 'Education/Islamic Studies' },
    { name: 'Education and Religious Studies' },
    { name: 'Education and Yoruba' },
    { name: 'History and Diplomatic Studies' },
    { name: 'Mass Communication' },
    { name: 'Nigerian Languages' },
    { name: 'Education and Music' },
    { name: 'Agricultural Education' },
    { name: 'Automobil Technology Education' },
    { name: 'Building Education' },
    { name: 'Computer Education' },
    { name: 'Computer and Information Technology' },
    { name: 'Geography and Environmental Management (Gem)' },
    { name: 'Education/Chemistry' },
    { name: 'Education and Computer Science' },
    { name: 'Education/Mathematics' },
    { name: 'Education/Science' },
    { name: 'Education/Technology/Introductory Education' },
    { name: 'Mathematics Education Technology' },
    { name: 'Electrical/Electronics Technology' },
    { name: 'Human Kinetics Education' },
    { name: 'Human Kinetics and Health Education' },
    { name: 'Industrial Chemistry' },
    { name: 'Industrial Technical Education' },
    { name: 'Mathematics/Statistics Education' },
    { name: 'Metal Technology Education' },
    { name: 'Petroleum and Petro-Chemical Sciences' },
    { name: 'Physical and Health Education' },
    { name: 'Physical Education' },
    { name: 'Physical Education and Recreation' },
    { name: 'Statistics' },
    { name: 'Sport Science' },
    { name: 'Technical Education' },
    { name: 'Telecommunication and Information Technology' },
    { name: 'Transport Planning and Management (TPM)' },
    { name: 'Theatre Arts' },
    { name: 'Technology Education' },
    { name: 'Technology and Vocation Education' },
    { name: 'Education/Integrated Science Education/Physics' },
    { name: 'Home Economics Education' },
    { name: 'Home Economics and Hotel Management' },
    { name: 'Intercultural Education' },
    { name: 'Education/Political Science' },
    { name: 'Education/Social Science' },
    { name: 'Education/Social Studies' },
    { name: 'Education/Sociology' },
    { name: 'Education/Accountancy' },
    { name: 'Economics/Geography' },
    { name: 'Education and Busines Administration' },
    { name: 'Business Education' },
    { name: 'Interculture Education' },
    { name: 'Secretarial Education' },
    { name: 'Social Work and Community Development' },
    { name: 'Vocational Education' },
    { name: 'Vocational Education and Technical Education' },
    { name: 'Civil Law' },
    { name: 'Common and Islamic Law' },
    { name: 'International Law and Jurisprudence' },
    { name: 'Islamic Law/Sharia Law' },
    { name: 'Private and Islamic Law' },
    { name: 'Public and International Law' },
    { name: 'Law' },
    { name: 'Common Law' },
    { name: 'Anatomy' },
    { name: 'Biochemistry' },
    { name: 'Dentistry and Dental Technology' },
    { name: 'Human Nutrition and Dietetics' },
    { name: 'Medical Biochemistry' },
    { name: 'Medical Rehabilitation' },
    { name: 'Medical Laboratory Technology/Science' },
    { name: 'Medicine and Surgery (Human Medicine)' },
    { name: 'Nursing/Nursing Science' },
    { name: 'Optometry' },
    { name: 'Pharmacy' },
    { name: 'Pharmacology' },
    { name: 'Physiology' },
    { name: 'Physiotherapy' },
    { name: 'Prosthesis and Orthopaedic Technology' },
    { name: 'Public Health Technology' },
    { name: 'Radiography' },
    { name: 'Veterinary Medicine' },
    { name: 'Animal and Environmental Biology' },
    { name: 'Anthropology' },
    { name: 'Applied Botany' },
    { name: 'Applied Biology' },
    { name: 'Biochemistry' },
    { name: 'Biochemistry and Molecular Biology' },
    { name: 'Forensic Science' },
    { name: 'Biological Science(s)' },
    { name: 'Physics' },
    { name: 'Microbiology' },
    { name: 'Plant Science and Biotechnology' },
    { name: 'Electronics' },
    { name: 'Physics and Electronics' },
    { name: 'Physics and Computer Electronic' },
    { name: 'Electrons' },
    { name: 'Physics and Solar Energy' },
    { name: 'Physics and Energy Studies' },
    { name: 'Physics/Industrial Physics' },
    { name: 'Physics with Computational Modeling' },
    { name: 'Physics/Astrology' },
    { name: 'Physical Sciences' },
    { name: 'Energy Studies' },
    { name: 'Physics and Applied Physics' },
    { name: 'Industrial Physics' },
    { name: 'Pure and Applied Physics' },
    { name: 'Applied Physics' },
    { name: 'Pure and Indurstrial Physics' },
    { name: 'Pure Physics' },
    { name: 'Industrial Physics an Renewable Energy' },
    { name: 'Industrial Physics with Electronics and its Application' },
    { name: 'Applied Biochemistry' },
    { name: 'Industrial Mathematics' },
    { name: 'Industrial Mathematics/Applied Statistics' },
    { name: 'Applied Mathematics and Statistics' },
    { name: 'Applied Statistics' },
    { name: 'Industrial Mathematics/Computer' },
    { name: 'Chemistry' },
    { name: 'Chemistry and Industrial Chemistry' },
    { name: 'Industrila Chemistry and Chemical Entrepreneurship' },
    { name: 'Pure Chemistry' },
    { name: 'Pure and Applied Chemistry' },
    { name: 'Chemical Scineces' },
    { name: 'Petroleum Chemistry' },
    { name: 'Industrial and Environmental Chemistry' },
    { name: 'Applied Chemistry' },
    { name: 'Food Science and Technology' },
    { name: 'Industrial Chemistry' },
    { name: 'Pure and Industrial Chemistry' },
    { name: 'Fisheries' },
    { name: 'Geology' },
    { name: 'Geological Scienes' },
    { name: 'Geology and Mineral' },
    { name: 'Geology and Geophysics' },
    { name: 'Geology and Mining' },
    { name: 'Geology and Petroleum Resources' },
    { name: 'Applied Geology' },
    { name: 'Geology and Mineeral Science' },
    { name: 'Marine Geology' },
    { name: 'Geography and Regonal Planning' },
    { name: 'Geography' },
    { name: 'Geography and Environmental Management' },
    { name: 'Surveying and Geoinformatics' },
    { name: 'Building Technology' },
    { name: 'Statistics' },
    { name: 'Biostatistics' },
    { name: 'Statistics and Data Sciences' },
    { name: 'Digital Entrepreneuship' },
    { name: 'Botany and Ecological Studies' },
    { name: 'Plant Biology and Biotechnology' },
    { name: 'Plant Sciene and Forestry' },
    { name: 'Plant Science and Microbiology' },
    { name: 'Plant Biology' },
    { name: 'Plant Science' },
    { name: 'Biotechnology' },
    { name: 'Genetics and Biotechnology' },
    { name: 'Ecology' },
    { name: 'Applied Ecology' },
    { name: 'Ecology and Environmental Studies' },
    { name: 'Zoology' },
    { name: 'Zoology and Aqaculture' },
    { name: 'Applied Zoology' },
    { name: 'Animal Biology and Environment' },
    { name: 'Zoology and Environmental Biology' },
    { name: 'Conversation Biology' },
    { name: 'Environmenatal Science and Technology' },
    { name: 'Environmtal Biology' },
    { name: 'Environmenatal Biology and Fisheries' },
    { name: 'Marine Science and Technology' },
    { name: 'Marine Science' },
    { name: 'Mathematics' },
    { name: 'Mathematics with Computer Science' },
    { name: 'Applied Geophysics' },
    { name: 'Geophysics' },
    { name: 'Geoscience' },
    { name: 'Geography and Geosciences' },
    { name: 'Earth Science' },
    { name: 'Sport Science' },
    { name: 'Microbiology' },
    { name: 'Microbiology and Biotechnology' },
    { name: 'Microbiology/Parsitology' },
    { name: 'Biology/Biotechnology' },
    { name: 'Molecular Biology' },
    { name: 'Microbiology and Indurstrial Biotechnology' },
    { name: 'Industrial Microbiology' },
    { name: 'Science Laboratory Technology' },
    { name: 'Natural and Environmenatal Health Science' },
    { name: 'Environmentl Health Science' },
    { name: 'Environmental Management' },
    { name: 'Environmental Management and Toxicology' },
    { name: 'Engergy and Petroleum Resources' },
    { name: 'Parisology and Entymology' },
    { name: 'Pure and Applied Mathematics' },
    { name: 'Mathematics and Economics' },
    { name: 'Mathematics with Economics' },
    { name: 'Applied Microbiology and Brewing' },
    { name: 'Applied Microbiology' },
    { name: 'Mathematics with Statistics' },
    { name: 'Mathematics and Statistics' },
    { name: 'Optometry' },
    { name: 'Computer Science' },
    { name: 'Computer, Informtion and Communication Science' },
    { name: 'Computer Science and Informatics' },
    { name: 'Computer Science and Information Technology' },
    { name: 'Computer Science and Information Science' },
    { name: 'Computer with Electronics' },
    { name: 'Software Engineering' },
    { name: 'Software Engineering and Digital Entrepreneurship' },
    { name: 'Information Technology' },
    { name: 'Data Management' },
    { name: 'Management Information System' },
    { name: 'Information Communication Technology' },
    { name: 'Information and Communication Science' },
    { name: 'Information Systems' },
    { name: 'Information Systems and Technology' },
    { name: 'Computer Science with Economics' },
    { name: 'Communication and Wireless Technology' },
    { name: 'Telecommunicatin Management' },
    { name: 'Telecommunication Science' },
    { name: 'Cyber Security Science' },
    { name: 'Cyber Computer Science' },
    { name: 'Cyber Security' },
    { name: 'Communications Technology' },
    { name: 'Library and Information Science' },
    { name: 'Information Science and Media Studies' },
    { name: 'Information Media Technology' },
    { name: 'Information Media Sciences' },
    { name: 'Mathematical Sciences' },
    { name: 'Computer Science and Mathematics' },
    { name: 'Computer Scince with Mathematics' },
    { name: 'Computer with Statistics' },
    { name: 'Electronics and Computer Technology' },
    { name: 'Archeaology' },
    { name: 'Biology' },
    { name: 'Human Biology' },
    { name: 'Pure and Applied Biology' },
    { name: 'Applied Botany' },
    { name: 'Applied Biology' },
    { name: 'Applied Biology and Genetics' },
    { name: 'Applied Biology and Biotechnology' },
    { name: 'Cell Biology and Genetics' },
    { name: 'Operational Research' },
    { name: 'Engineering Physics' },
    { name: 'Bioinformatics' },
    { name: 'Anthroplolgy (Biological)' },
    { name: 'Marine Biology and Fisheries' },
    { name: 'Marine Biology' },
    { name: 'Fisheries and Aquaculture' },
    { name: 'Ocenography' },
    { name: 'Accountancy/Finance/Accounting' },
    { name: 'Accounting Management 8 Finance' },
    { name: 'Anthroplogy' },
    { name: 'Actuarial Science' },
    { name: 'Arabic and Islamic Religious Studies' },
    { name: 'Banking and Finance' },
    { name: 'Business Mangemnt/Mangement Sciences' },
    { name: 'Business Adminsistration' },
    { name: 'Business and Entreprenerual Studies' },
    { name: 'Criminology' },
    { name: 'Crimnology and Penology' },
    { name: 'Criminology and Security Studies' },
    { name: 'Demography and Social Statistics' },
    { name: 'Economics' },
    { name: 'Entrepreneurship' },
    { name: 'Entrepreneural Studies' },
    { name: 'Entrepreneurship Studies and innovation' },
    { name: 'Economics and Development Studies' },
    { name: 'Econmics and Operation Research' },
    { name: 'Economics and Statistics' },
    { name: 'Environmental Protection and Resources Management' },
    { name: 'Film and Video Studies' },
    { name: 'Finance' },
    { name: 'Geography' },
    { name: 'Geography and Environmental Mangement' },
    { name: 'Geography and Meteorology' },
    { name: 'Geography and Regional Planning' },
    { name: 'Geography and Planning' },
    { name: 'Government and Public Administration' },
    { name: 'Hospitality and Toursm' },
    { name: 'Hospitality and Toursim Management' },
    { name: 'Hotel Managemtn and TOursim' },
    { name: 'Human Resources Management' },
    { name: 'Industrial Relations and Personnel Management' },
    { name: 'Intelligence and Security Studies' },
    { name: 'Insurance' },
    { name: 'Internationl Relations' },
    { name: 'International Relations nd Diplomacy' },
    { name: 'International Relationship and Strategic Studies' },
    { name: 'International Studies' },
    { name: 'International Studies and Diplomacy' },
    { name: 'International and Comparative Politics' },
    { name: 'Library and Information Science' },
    { name: 'Library Science' },
    { name: 'Management and Entrepreneruship' },
    { name: 'Marketing' },
    { name: 'Marketing and Advertising' },
    { name: 'Mass Communication' },
    { name: 'Mass Communication and Media Technology' },
    { name: 'Media and Communication Studies' },
    { name: 'Office and Informtion Mangement' },
    { name: 'Peace and Development Studies' },
    { name: 'Peace and Conflict Studies' },
    { name: 'Peace Studies and Conflict Resolution' },
    { name: 'Philosophy' },
    { name: 'Polictical Science' },
    { name: 'Polictical Science and Diplomacy' },
    { name: 'Polictical Science/International Law and Diplomacy' },
    { name: 'Polictical Science and Administrative Studies' },
    { name: 'Polictical Science and International Relations' },
    { name: 'Polictical Science and Conflict Resolution' },
    { name: 'Polictical Science and Defence Studies' },
    { name: 'Policy and Strategic Studies' },
    { name: 'Policy and Administrative Studies' },
    { name: 'Population Studies' },
    { name: 'Psychology' },
    { name: 'Public Adminstation' },
    { name: 'Public Adminstation and Local Government' },
    { name: 'Religious Studies' },
    { name: 'Social Justice' },
    { name: 'Social Work' },
    { name: 'Sociology' },
    { name: 'Sociology and Anthropology' },
    { name: 'Transport Management' },
    { name: 'Transport Planning and Mangement' },
    { name: 'Taxation' },
    { name: 'Taxation and Event Mangement' },
    { name: 'Toursim Studies' }
]